### ISSUE TITLE
Import using package: prefix

### ISSUE THREAD

**Issue by efreibe** [eernstg/reflectable-flutter#2] opened 2018-10-03 21:21 UTC
Hello, I've made a test project using Reflectable.
My project did not work as expected and I lost several hours trying to find out what was happening.
Finally I found that changing a package prefix in the imports makes it work, but the question is:

What is the difference between 
```dart
import 'package:flutter/material.dart';
import 'package:reflectable_flutter/do_reflect.dart';
import 'main.reflectable.dart';
```
and
```dart
import 'package:flutter/material.dart';
import 'do_reflect.dart';
import 'main.reflectable.dart';
```
because if I use the latter then I get assertion errors like this:

> I/flutter (32261): #2      _DataCaching._data (package:reflectable/src/reflectable_builder_based.dart:197:14)
> I/flutter (32261): #3      new _InstanceMirrorImpl (package:reflectable/src/reflectable_builder_based.dart:208:13)
> I/flutter (32261): #4      ReflectableImpl.reflect (package:reflectable/src/reflectable_builder_based.dart:2492:16)
> I/flutter (32261): #5      doReflect (file:///Users/ernestofreiberg/github/reflectable_flutter/lib/do_reflect.dart:44:49)
> I/flutter (32261): #6      _MyHomePageState.build (file:///Users/ernestofreiberg/github/reflectable_flutter/lib/main.dart:107:20)

Sorry if I missed a language feature o something like that but I did not found any information about any difference in using a package prefix.

**Comment by eernstg** [comment] 2018-10-04 11:48
The relative import directive `import 'do_reflect.dart';` requires the file that contains the imported library to be in the same directory as the file that contains the import directive, and the `package:` import will fetch the library from said package. If you use both forms in the same program for any given library _L_ then the runtime may be unable to detect that it is the same library, and this means that you can get duplicates of the declarations.

For instance, you might have "two copies" of `class A ..` declared in `do_reflect.dart`, where one is accessed via the relative URI and the other one via the package URI. They may have the same supertypes, but the two types have nothing to do with each other (they are not equal, and neither is a subtype of the other), so you may have failing dynamic type checks because of that.

So I'd suggest that you standardize on always using relative URIs among libraries inside the `lib` of a given package, and `package` for anything that reaches across the boundary between one library and another one, and also for `example`, `test`, and similar subdirectories of a package _P_ when referring to libraries in the `lib` directory of _P_.

It's not very nice that such a thing can happen, but you could of course use symlinks (or even hard links) to get "two different copies of the same library", so we couldn't ever expect tools to be able to detect that they should really be "the same" (including: "the same types").

So that's step one.

For step two I'd need to know more about how your software actually fails (I cannot see any assertion violations in the output that you provided).

**Comment by efreibe** [comment] 2018-10-04 14:25
Hello, thank you for the explanation. I have no duplicates in the project. It is a clone of this repository.

As for the second step, I have not provided any output because I forgot to mention that you can reproduce the error simply cloning this repo and removing the prefix package: in this way:

```dart
import 'package:reflectable_flutter/do_reflect.dart';
```
with
```dart
import 'do_reflect.dart';
```

I am using the latest version of flutter in master channel.

You can see this issue also:
https://github.com/dart-lang/reflectable/issues/117

Thank you

**Comment by eernstg** [comment] 2018-10-05 14:02
> I have no duplicates in the project.

The problem is not that you have two identical files or two copies of any declaration, the problem is that your project accesses a single file via two different URIs, and consequently the language semantics "thinks" that there are two copies of each of the declarations in that file.

That's a bad situation and it should be fixed in any case (surely other things will break if you have two copies of every static variable in some classes, and different parts of your program will see one or the other; and you have two copies of a bunch of types that makes `x = y` an error because they both have type `T` but it's not the same `T`, etc). In this particular case it breaks reflectable, but that's just one example.

I tried to do what you described (changing the `package` URI to a relative one in `main.dart`), and I get a dynamic error which is probably the same thing that you've seen. But the actual error message is as follows:

```
I/flutter ( 5683): 'package:reflectable/src/reflectable_builder_based.dart': Failed assertion: line 197 pos 14:
I/flutter ( 5683): '_dataCache != null': is not true.
```

This is exactly what you'd expect if you get two copies of `myReflectable` and then one of them is used to look up something (as in `reflectable_builder_based.dart` line 193: `_dataCache = data[_reflector];`) and then you don't find it because that map entry has the other copy as its key (and then you get the assertion error on `assert(_dataCache != null)` in line 197).

In the experiment I made (which would essentially be the same thing as what you've described), I can see the following instance of this problem:

```dart
lib/main.dart
2:import 'do_reflect.dart';

lib/main.reflectable.dart
5:import 'package:reflectable_flutter/do_reflect.dart' as prefix0;
```

I can eliminate the dynamic error by changing `'do_reflect.dart'` to `'package:reflectable_flutter/do_reflect.dart'` in `main.dart`, and I can eliminate it by performing the opposite change in `main.reflectable.dart` (but, of course, not both at the same time, because then you just recreate the problem).

The reason why `do_reflect.dart` is accessed by a `package:` URI (which is something that the analyzer decides and reports to reflectable) is probably that it is _possible_ to do so, and a `package:` URI is an obvious choice for an expressive normal form for URIs (relative URIs don't work for libraries outside the current package). If the entry point `main.dart` had been located outside `lib` (which would be the case for anything other than Flutter, e.g., it could be in `bin` or `test`) then the `package:` URI would have been strongly recommended (over something like `import '../lib/do_reflect.dart'` which might not even work at all), so the whole problem arises because there is this clash between the general Dart rule that "entry points go into one of [these directories](https://www.dartlang.org/tools/pub/glossary#entrypoint-directory)", but Flutter recommends that you put an entry point (`main.dart`) into `lib`, which is not one of those directories.

I think the rule of thumb that should help avoiding this problem is to think that even though `main.dart` in a Flutter project is located in `lib`, it should use `package:` imports for _every_ library where that is possible.

**Comment by eernstg** [comment] 2018-10-05 14:23
Another matter is that the version constraints for using reflectable in the context of flutter do not match up: In reflectable, the pubspec.yaml constraint on the analyzer is `^0.32.0`, but Flutter requires exactly `0.33.0-alpha.0`. This conflict can be resolved with an override in your `pubspec.yaml`:

```yaml
dependency_overrides:
  analyzer: 0.33.0-alpha.0
```

I can't see any other way to get this (changes to the constraints in reflectable do not make it possible to find a version constraint solution, because no version of `build` allows analyzer `0.33.0-alpha.0`). So we'll have to find a better solution for that later on, but right now you'll have to use the override.

**Comment by efreibe** [comment] 2018-10-05 15:00
Now I got it right. Excellent explanation.

Thank you for the time you took to write it down, I think this could help many people to save some time figuring out what the error was, and even as trivial as it sounds, the least part of the code you will look at is inside an import directive that IS actually working.

As you say, the best we can do in this case is keep this as a side note for flutter developers, and take the files as if they were part of a library.

I do not know if possible but maybe the builder could analyze the folder struct and generate the files without the package directives in case the original file is local to the project, said that, I don't think it'll worth the try.

Regarding the dependencies, I included the same override in the yaml file.

Another possibility in this particular case is to remove the unneeded test unit libraries for now.

**Closed as completed** 2019-09-19 18:22 UTC
